"""
Seed data for Squalo swim locations.
This file contains the swimming locations for Berlin that should be available in the Squalo webapp.
"""

# Initial Squalo swim locations (Step 1: 3 core locations)
# This list includes the first 3 locations to start with
SWIM_LOCATIONS = [
    # Core Berlin locations (Step 1)
    {
        "name": "Stadtbad Tiergarten",
        "location_type": "Schwimmbad",
        "district": "Mitte",
        "address": "MoltkestraÃŸe 32, 10785 Berlin",
        "latitude": 52.5040,
        "longitude": 13.3429,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "25Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Stadtbad+Tiergarten+Berlin"
    },
    {
        "name": "Sommerbad NeukÃ¶lln",
        "location_type": "Sommerbad",
        "district": "NeukÃ¶lln",
        "address": "Richard-Hartmann-StraÃŸe 60, 12057 Berlin",
        "latitude": 52.4560,
        "longitude": 13.4280,
        "official_status": "open",
        "verified_status": "not_verified",
        "water_temperature": "22Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Sommerbad+NeukÃ¶lln+Berlin"
    },
    {
        "name": "Strandbad PlÃ¶tzensee",
        "location_type": "Strandbad",
        "district": "Reinickendorf",
        "address": "Am Strandbad 1, 13187 Berlin",
        "latitude": 52.6000,
        "longitude": 13.2833,
        "official_status": "closed",
        "verified_status": "verified",
        "water_temperature": "18Â°C",
        "crowd_level": "high",
        "maps_url": "https://maps.google.com/?q=Strandbad+PlÃ¶tzensee+Berlin"
    },
    # Step 2: Next 3 locations
    {
        "name": "Kombibad SeestraÃŸe",
        "location_type": "Kombibad",
        "district": "Charlottenburg",
        "address": "SeestraÃŸe 28, 10555 Berlin",
        "latitude": 52.5280,
        "longitude": 13.3167,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "28Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Kombibad+SeestraÃŸe+Berlin"
    },
    {
        "name": "Schwimm- und Sprunghalle im Europasportpark",
        "location_type": "Kombibad",
        "district": "NeukÃ¶lln",
        "address": "Olympiapromenade 2, 10829 Berlin",
        "latitude": 52.4975,
        "longitude": 13.3306,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "26Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Sprunghalle+Europasportpark+Berlin"
    },
    {
        "name": "Prinzenbad",
        "location_type": "Sommerbad",
        "district": "Mitte",
        "address": "Friedrichsgracht 32, 10178 Berlin",
        "latitude": 52.5040,
        "longitude": 13.3429,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "24Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Prinzenbad+Berlin"
    },
    # Step 3: Next 6 locations
    {
        "name": "Stadtbad Charlottenburg â€“ Alte Halle",
        "location_type": "Schwimmbad",
        "district": "Charlottenburg",
        "address": "Oderberger StraÃŸe 57, 10119 Berlin",
        "latitude": 52.5280,
        "longitude": 13.3167,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "27Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Stadtbad+Charlottenburg+Berlin"
    },
    {
        "name": "Flughafensee",
        "location_type": "See",
        "district": "Reinickendorf",
        "address": "Am Flughafensee, 13187 Berlin",
        "latitude": 52.6333,
        "longitude": 13.2833,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "20Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Flughafensee+Berlin"
    },
    {
        "name": "Strandbad Wannsee",
        "location_type": "Strandbad",
        "district": "Steglitz-Zehlendorf",
        "address": "Am Wannsee 1, 14129 Berlin",
        "latitude": 52.4333,
        "longitude": 13.1667,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "22Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Strandbad+Wannsee+Berlin"
    },
    {
        "name": "Stadtbad SchÃ¶neberg",
        "location_type": "Schwimmbad",
        "district": "SchÃ¶neberg",
        "address": "JohannestraÃŸe 2, 10629 Berlin",
        "latitude": 52.4833,
        "longitude": 13.3333,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "26Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Stadtbad+SchÃ¶neberg+Berlin"
    },
    {
        "name": "Stadtbad Wilmersdorf I",
        "location_type": "Schwimmbad",
        "district": "Wilmersdorf",
        "address": "KleiststraÃŸe 1, 10719 Berlin",
        "latitude": 52.5167,
        "longitude": 13.3167,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "25Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Stadtbad+Wilmersdorf+Berlin"
    },
    {
        "name": "Stadtbad Wilmersdorf II",
        "location_type": "Schwimmbad",
        "district": "Wilmersdorf",
        "address": "KleiststraÃŸe 1, 10719 Berlin",
        "latitude": 52.5167,
        "longitude": 13.3167,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "25Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Stadtbad+Wilmersdorf+Berlin"
    },
    # Step 4: Next 6 locations
    {
        "name": "Kombibad Gropiusstadt â€“ Halle",
        "location_type": "Kombibad",
        "district": "NeukÃ¶lln",
        "address": "Gropiusstadt 12, 12349 Berlin",
        "latitude": 52.4333,
        "longitude": 13.4667,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "28Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Kombibad+Gropiusstadt+Berlin"
    },
    {
        "name": "Kombibad Gropiusstadt â€“ Sommerbad",
        "location_type": "Sommerbad",
        "district": "NeukÃ¶lln",
        "address": "Gropiusstadt 12, 12349 Berlin",
        "latitude": 52.4333,
        "longitude": 13.4667,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "24Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Kombibad+Gropiusstadt+Sommerbad+Berlin"
    },
    {
        "name": "Sommerbad Kreuzberg",
        "location_type": "Sommerbad",
        "district": "Kreuzberg",
        "address": "FalkenstraÃŸe 36, 10965 Berlin",
        "latitude": 52.4833,
        "longitude": 13.4167,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "23Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Sommerbad+Kreuzberg+Berlin"
    },
    {
        "name": "Sommerbad Olympiastadion",
        "location_type": "Sommerbad",
        "district": "Charlottenburg",
        "address": "Olympiapark, 10587 Berlin",
        "latitude": 52.5167,
        "longitude": 13.2833,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "26Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Sommerbad+Olympiastadion+Berlin"
    },
    {
        "name": "Kombibad Spandau SÃ¼d",
        "location_type": "Kombibad",
        "district": "Spandau",
        "address": "Am SÃ¼dpark 1, 13597 Berlin",
        "latitude": 52.5333,
        "longitude": 13.1833,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "27Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Kombibad+Spandau+SÃ¼d+Berlin"
    },
    {
        "name": "Stadtbad Lankwitz",
        "location_type": "Schwimmbad",
        "district": "Steglitz-Zehlendorf",
        "address": "Lankwitzer StraÃŸe 41, 12209 Berlin",
        "latitude": 52.4167,
        "longitude": 13.3000,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "25Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Stadtbad+Lankwitz+Berlin"
    },
    # Step 5: Next 6 locations
    {
        "name": "Tegeler See",
        "location_type": "See",
        "district": "Reinickendorf",
        "address": "Am Tegeler See, 13403 Berlin",
        "latitude": 52.6333,
        "longitude": 13.2833,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "19Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Tegeler+See+Berlin"
    },
    {
        "name": "Stadtbad Fischerinsel",
        "location_type": "Schwimmbad",
        "district": "Mitte",
        "address": "Fischerinsel 1, 10179 Berlin",
        "latitude": 52.5167,
        "longitude": 13.4000,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "24Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Stadtbad+Fischerinsel+Berlin"
    },
    {
        "name": "MÃ¼ggelsee",
        "location_type": "See",
        "district": "Treptow-KÃ¶penick",
        "address": "Am MÃ¼ggelsee, 12587 Berlin",
        "latitude": 52.4333,
        "longitude": 13.5667,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "21Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=MÃ¼ggelsee+Berlin"
    },
    {
        "name": "Strandbad Friedrichshagen",
        "location_type": "Strandbad",
        "district": "Treptow-KÃ¶penick",
        "address": "Friedrichshagener StraÃŸe 221, 12527 Berlin",
        "latitude": 52.4333,
        "longitude": 13.5667,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "22Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Strandbad+Friedrichshagen+Berlin"
    },
    {
        "name": "James Simon Stadtbad",
        "location_type": "Schwimmbad",
        "district": "Mitte",
        "address": "Unter den Linden 40, 10117 Berlin",
        "latitude": 52.5167,
        "longitude": 13.3833,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "25Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=James+Simon+Stadtbad+Berlin"
    },
    {
        "name": "Arena Badeschiff",
        "location_type": "Outdoor",
        "district": "Mitte",
        "address": "Eiserne Bridge 1, 10179 Berlin",
        "latitude": 52.5167,
        "longitude": 13.3833,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "28Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Arena+Badeschiff+Berlin"
    },
    # Step 6: Next 6 locations
    {
        "name": "Schlachtensee",
        "location_type": "See",
        "district": "Zehlendorf",
        "address": "Schlachtensee, 14129 Berlin",
        "latitude": 52.4333,
        "longitude": 13.2000,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "18Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Schlachtensee+Berlin"
    },
    {
        "name": "Krumme Lanke",
        "location_type": "See",
        "district": "Zehlendorf",
        "address": "Krumme Lanke, 14129 Berlin",
        "latitude": 52.4333,
        "longitude": 13.2000,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "19Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Krumme+Lanke+Berlin"
    },
    {
        "name": "Sommerbad Humboldthain",
        "location_type": "Sommerbad",
        "district": "Mitte",
        "address": "BÃ¶tzowstraÃŸe 32, 10178 Berlin",
        "latitude": 52.5333,
        "longitude": 13.4000,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "22Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Sommerbad+Humboldthain+Berlin"
    },
    {
        "name": "Strandbad WeiÃŸensee",
        "location_type": "Strandbad",
        "district": "WeiÃŸensee",
        "address": "Am WeiÃŸensee, 13086 Berlin",
        "latitude": 52.5333,
        "longitude": 13.4000,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "23Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Strandbad+WeiÃŸensee+Berlin"
    },
    {
        "name": "Freibad Jungfernheide / Strandbad Jungfernheide",
        "location_type": "Outdoor",
        "district": "Charlottenburg",
        "address": "JÃ¤gerallee 55, 10785 Berlin",
        "latitude": 52.5167,
        "longitude": 13.3167,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "24Â°C",
        "crowd_level": "medium",
        "maps_url": "https://maps.google.com/?q=Freibad+Jungfernheide+Berlin"
    },
    {
        "name": "Strandbad Orankesee",
        "location_type": "Strandbad",
        "district": "MÃ¼ggelheim",
        "address": "Am Orankesee, 12587 Berlin",
        "latitude": 52.4333,
        "longitude": 13.5667,
        "official_status": "open",
        "verified_status": "verified",
        "water_temperature": "20Â°C",
        "crowd_level": "low",
        "maps_url": "https://maps.google.com/?q=Strandbad+Orankesee+Berlin"
    },
]
